# build stage
FROM golang:1.22 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/demoapi ./cmd/demoapi

# runtime stage
FROM debian:12-slim
WORKDIR /srv
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=build /out/demoapi /srv/demoapi
ENV DEMOAPI_LISTEN_ADDR=:9090
USER root
CMD ["/srv/demoapi"]
