// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: api/credit/v1/credit.proto

package creditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntryId        string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	CreatedUnixUtc int64                  `protobuf:"varint,2,opt,name=created_unix_utc,json=createdUnixUtc,proto3" json:"created_unix_utc,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{0}
}

func (x *Empty) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *Empty) GetCreatedUnixUtc() int64 {
	if x != nil {
		return x.CreatedUnixUtc
	}
	return 0
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountCents   int64                  `protobuf:"varint,1,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{1}
}

func (x *Amount) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LedgerId      string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{2}
}

func (x *BalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BalanceRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *BalanceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type BalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalCents     int64                  `protobuf:"varint,1,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	AvailableCents int64                  `protobuf:"varint,2,opt,name=available_cents,json=availableCents,proto3" json:"available_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceResponse) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *BalanceResponse) GetAvailableCents() int64 {
	if x != nil {
		return x.AvailableCents
	}
	return 0
}

type GrantRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents      int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpiresAtUnixUtc int64                  `protobuf:"varint,4,opt,name=expires_at_unix_utc,json=expiresAtUnixUtc,proto3" json:"expires_at_unix_utc,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId         string                 `protobuf:"bytes,6,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{4}
}

func (x *GrantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *GrantRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *GrantRequest) GetExpiresAtUnixUtc() int64 {
	if x != nil {
		return x.ExpiresAtUnixUtc
	}
	return 0
}

func (x *GrantRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *GrantRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *GrantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ReserveRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents      int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	ReservationId    string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId         string                 `protobuf:"bytes,6,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExpiresAtUnixUtc int64                  `protobuf:"varint,8,opt,name=expires_at_unix_utc,json=expiresAtUnixUtc,proto3" json:"expires_at_unix_utc,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *ReserveRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReserveRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *ReserveRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *ReserveRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReserveRequest) GetExpiresAtUnixUtc() int64 {
	if x != nil {
		return x.ExpiresAtUnixUtc
	}
	return 0
}

type CaptureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReservationId  string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AmountCents    int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId       string                 `protobuf:"bytes,6,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{6}
}

func (x *CaptureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CaptureRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CaptureRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CaptureRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CaptureRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *CaptureRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *CaptureRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ReleaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReservationId  string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId       string                 `protobuf:"bytes,5,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReleaseRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReleaseRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *ReleaseRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *ReleaseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SpendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents    int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId       string                 `protobuf:"bytes,5,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpendRequest) Reset() {
	*x = SpendRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendRequest) ProtoMessage() {}

func (x *SpendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendRequest.ProtoReflect.Descriptor instead.
func (*SpendRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{8}
}

func (x *SpendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SpendRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *SpendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SpendRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *SpendRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *SpendRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RefundRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	UserId   string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LedgerId string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Types that are valid to be assigned to Original:
	//
	//	*RefundRequest_OriginalEntryId
	//	*RefundRequest_OriginalIdempotencyKey
	Original       isRefundRequest_Original `protobuf_oneof:"original"`
	AmountCents    int64                    `protobuf:"varint,6,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey string                   `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                   `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{9}
}

func (x *RefundRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefundRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *RefundRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RefundRequest) GetOriginal() isRefundRequest_Original {
	if x != nil {
		return x.Original
	}
	return nil
}

func (x *RefundRequest) GetOriginalEntryId() string {
	if x != nil {
		if x, ok := x.Original.(*RefundRequest_OriginalEntryId); ok {
			return x.OriginalEntryId
		}
	}
	return ""
}

func (x *RefundRequest) GetOriginalIdempotencyKey() string {
	if x != nil {
		if x, ok := x.Original.(*RefundRequest_OriginalIdempotencyKey); ok {
			return x.OriginalIdempotencyKey
		}
	}
	return ""
}

func (x *RefundRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *RefundRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RefundRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type isRefundRequest_Original interface {
	isRefundRequest_Original()
}

type RefundRequest_OriginalEntryId struct {
	OriginalEntryId string `protobuf:"bytes,4,opt,name=original_entry_id,json=originalEntryId,proto3,oneof"`
}

type RefundRequest_OriginalIdempotencyKey struct {
	OriginalIdempotencyKey string `protobuf:"bytes,5,opt,name=original_idempotency_key,json=originalIdempotencyKey,proto3,oneof"`
}

func (*RefundRequest_OriginalEntryId) isRefundRequest_Original() {}

func (*RefundRequest_OriginalIdempotencyKey) isRefundRequest_Original() {}

type RefundResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EntryId        string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	CreatedUnixUtc int64                  `protobuf:"varint,2,opt,name=created_unix_utc,json=createdUnixUtc,proto3" json:"created_unix_utc,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{10}
}

func (x *RefundResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *RefundResponse) GetCreatedUnixUtc() int64 {
	if x != nil {
		return x.CreatedUnixUtc
	}
	return 0
}

type Entry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntryId          string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	AccountId        string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AmountCents      int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	ReservationId    string                 `protobuf:"bytes,5,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpiresAtUnixUtc int64                  `protobuf:"varint,7,opt,name=expires_at_unix_utc,json=expiresAtUnixUtc,proto3" json:"expires_at_unix_utc,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedUnixUtc   int64                  `protobuf:"varint,9,opt,name=created_unix_utc,json=createdUnixUtc,proto3" json:"created_unix_utc,omitempty"`
	RefundOfEntryId  string                 `protobuf:"bytes,10,opt,name=refund_of_entry_id,json=refundOfEntryId,proto3" json:"refund_of_entry_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{11}
}

func (x *Entry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *Entry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entry) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Entry) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *Entry) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Entry) GetExpiresAtUnixUtc() int64 {
	if x != nil {
		return x.ExpiresAtUnixUtc
	}
	return 0
}

func (x *Entry) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *Entry) GetCreatedUnixUtc() int64 {
	if x != nil {
		return x.CreatedUnixUtc
	}
	return 0
}

func (x *Entry) GetRefundOfEntryId() string {
	if x != nil {
		return x.RefundOfEntryId
	}
	return ""
}

type ListEntriesRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UserId               string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BeforeUnixUtc        int64                  `protobuf:"varint,2,opt,name=before_unix_utc,json=beforeUnixUtc,proto3" json:"before_unix_utc,omitempty"`
	Limit                int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	LedgerId             string                 `protobuf:"bytes,4,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId             string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Types                []string               `protobuf:"bytes,6,rep,name=types,proto3" json:"types,omitempty"`
	ReservationId        string                 `protobuf:"bytes,7,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKeyPrefix string                 `protobuf:"bytes,8,opt,name=idempotency_key_prefix,json=idempotencyKeyPrefix,proto3" json:"idempotency_key_prefix,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{12}
}

func (x *ListEntriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListEntriesRequest) GetBeforeUnixUtc() int64 {
	if x != nil {
		return x.BeforeUnixUtc
	}
	return 0
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntriesRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *ListEntriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListEntriesRequest) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ListEntriesRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ListEntriesRequest) GetIdempotencyKeyPrefix() string {
	if x != nil {
		return x.IdempotencyKeyPrefix
	}
	return ""
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{13}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AccountContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LedgerId      string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountContext) Reset() {
	*x = AccountContext{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountContext) ProtoMessage() {}

func (x *AccountContext) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountContext.ProtoReflect.Descriptor instead.
func (*AccountContext) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{14}
}

func (x *AccountContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountContext) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *AccountContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type BatchGrantOp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AmountCents      int64                  `protobuf:"varint,1,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpiresAtUnixUtc int64                  `protobuf:"varint,3,opt,name=expires_at_unix_utc,json=expiresAtUnixUtc,proto3" json:"expires_at_unix_utc,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchGrantOp) Reset() {
	*x = BatchGrantOp{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGrantOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGrantOp) ProtoMessage() {}

func (x *BatchGrantOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGrantOp.ProtoReflect.Descriptor instead.
func (*BatchGrantOp) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{15}
}

func (x *BatchGrantOp) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BatchGrantOp) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BatchGrantOp) GetExpiresAtUnixUtc() int64 {
	if x != nil {
		return x.ExpiresAtUnixUtc
	}
	return 0
}

func (x *BatchGrantOp) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchReserveOp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AmountCents      int64                  `protobuf:"varint,1,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	ReservationId    string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	ExpiresAtUnixUtc int64                  `protobuf:"varint,5,opt,name=expires_at_unix_utc,json=expiresAtUnixUtc,proto3" json:"expires_at_unix_utc,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchReserveOp) Reset() {
	*x = BatchReserveOp{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReserveOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReserveOp) ProtoMessage() {}

func (x *BatchReserveOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReserveOp.ProtoReflect.Descriptor instead.
func (*BatchReserveOp) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{16}
}

func (x *BatchReserveOp) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BatchReserveOp) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *BatchReserveOp) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BatchReserveOp) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *BatchReserveOp) GetExpiresAtUnixUtc() int64 {
	if x != nil {
		return x.ExpiresAtUnixUtc
	}
	return 0
}

type BatchCaptureOp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AmountCents    int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchCaptureOp) Reset() {
	*x = BatchCaptureOp{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCaptureOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCaptureOp) ProtoMessage() {}

func (x *BatchCaptureOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCaptureOp.ProtoReflect.Descriptor instead.
func (*BatchCaptureOp) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{17}
}

func (x *BatchCaptureOp) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *BatchCaptureOp) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BatchCaptureOp) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BatchCaptureOp) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchReleaseOp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReservationId  string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchReleaseOp) Reset() {
	*x = BatchReleaseOp{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchReleaseOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchReleaseOp) ProtoMessage() {}

func (x *BatchReleaseOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchReleaseOp.ProtoReflect.Descriptor instead.
func (*BatchReleaseOp) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{18}
}

func (x *BatchReleaseOp) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *BatchReleaseOp) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BatchReleaseOp) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchSpendOp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AmountCents    int64                  `protobuf:"varint,1,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,3,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchSpendOp) Reset() {
	*x = BatchSpendOp{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSpendOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSpendOp) ProtoMessage() {}

func (x *BatchSpendOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSpendOp.ProtoReflect.Descriptor instead.
func (*BatchSpendOp) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{19}
}

func (x *BatchSpendOp) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BatchSpendOp) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BatchSpendOp) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type BatchRefundOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Original:
	//
	//	*BatchRefundOp_OriginalEntryId
	//	*BatchRefundOp_OriginalIdempotencyKey
	Original       isBatchRefundOp_Original `protobuf_oneof:"original"`
	AmountCents    int64                    `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey string                   `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                   `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchRefundOp) Reset() {
	*x = BatchRefundOp{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRefundOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRefundOp) ProtoMessage() {}

func (x *BatchRefundOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRefundOp.ProtoReflect.Descriptor instead.
func (*BatchRefundOp) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{20}
}

func (x *BatchRefundOp) GetOriginal() isBatchRefundOp_Original {
	if x != nil {
		return x.Original
	}
	return nil
}

func (x *BatchRefundOp) GetOriginalEntryId() string {
	if x != nil {
		if x, ok := x.Original.(*BatchRefundOp_OriginalEntryId); ok {
			return x.OriginalEntryId
		}
	}
	return ""
}

func (x *BatchRefundOp) GetOriginalIdempotencyKey() string {
	if x != nil {
		if x, ok := x.Original.(*BatchRefundOp_OriginalIdempotencyKey); ok {
			return x.OriginalIdempotencyKey
		}
	}
	return ""
}

func (x *BatchRefundOp) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *BatchRefundOp) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *BatchRefundOp) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type isBatchRefundOp_Original interface {
	isBatchRefundOp_Original()
}

type BatchRefundOp_OriginalEntryId struct {
	OriginalEntryId string `protobuf:"bytes,1,opt,name=original_entry_id,json=originalEntryId,proto3,oneof"`
}

type BatchRefundOp_OriginalIdempotencyKey struct {
	OriginalIdempotencyKey string `protobuf:"bytes,2,opt,name=original_idempotency_key,json=originalIdempotencyKey,proto3,oneof"`
}

func (*BatchRefundOp_OriginalEntryId) isBatchRefundOp_Original() {}

func (*BatchRefundOp_OriginalIdempotencyKey) isBatchRefundOp_Original() {}

type BatchOperation struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OperationId string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Types that are valid to be assigned to Operation:
	//
	//	*BatchOperation_Grant
	//	*BatchOperation_Spend
	//	*BatchOperation_Reserve
	//	*BatchOperation_Capture
	//	*BatchOperation_Release
	//	*BatchOperation_Refund
	Operation     isBatchOperation_Operation `protobuf_oneof:"operation"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperation) Reset() {
	*x = BatchOperation{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperation) ProtoMessage() {}

func (x *BatchOperation) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperation.ProtoReflect.Descriptor instead.
func (*BatchOperation) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{21}
}

func (x *BatchOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *BatchOperation) GetOperation() isBatchOperation_Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *BatchOperation) GetGrant() *BatchGrantOp {
	if x != nil {
		if x, ok := x.Operation.(*BatchOperation_Grant); ok {
			return x.Grant
		}
	}
	return nil
}

func (x *BatchOperation) GetSpend() *BatchSpendOp {
	if x != nil {
		if x, ok := x.Operation.(*BatchOperation_Spend); ok {
			return x.Spend
		}
	}
	return nil
}

func (x *BatchOperation) GetReserve() *BatchReserveOp {
	if x != nil {
		if x, ok := x.Operation.(*BatchOperation_Reserve); ok {
			return x.Reserve
		}
	}
	return nil
}

func (x *BatchOperation) GetCapture() *BatchCaptureOp {
	if x != nil {
		if x, ok := x.Operation.(*BatchOperation_Capture); ok {
			return x.Capture
		}
	}
	return nil
}

func (x *BatchOperation) GetRelease() *BatchReleaseOp {
	if x != nil {
		if x, ok := x.Operation.(*BatchOperation_Release); ok {
			return x.Release
		}
	}
	return nil
}

func (x *BatchOperation) GetRefund() *BatchRefundOp {
	if x != nil {
		if x, ok := x.Operation.(*BatchOperation_Refund); ok {
			return x.Refund
		}
	}
	return nil
}

type isBatchOperation_Operation interface {
	isBatchOperation_Operation()
}

type BatchOperation_Grant struct {
	Grant *BatchGrantOp `protobuf:"bytes,2,opt,name=grant,proto3,oneof"`
}

type BatchOperation_Spend struct {
	Spend *BatchSpendOp `protobuf:"bytes,3,opt,name=spend,proto3,oneof"`
}

type BatchOperation_Reserve struct {
	Reserve *BatchReserveOp `protobuf:"bytes,4,opt,name=reserve,proto3,oneof"`
}

type BatchOperation_Capture struct {
	Capture *BatchCaptureOp `protobuf:"bytes,5,opt,name=capture,proto3,oneof"`
}

type BatchOperation_Release struct {
	Release *BatchReleaseOp `protobuf:"bytes,6,opt,name=release,proto3,oneof"`
}

type BatchOperation_Refund struct {
	Refund *BatchRefundOp `protobuf:"bytes,7,opt,name=refund,proto3,oneof"`
}

func (*BatchOperation_Grant) isBatchOperation_Operation() {}

func (*BatchOperation_Spend) isBatchOperation_Operation() {}

func (*BatchOperation_Reserve) isBatchOperation_Operation() {}

func (*BatchOperation_Capture) isBatchOperation_Operation() {}

func (*BatchOperation_Release) isBatchOperation_Operation() {}

func (*BatchOperation_Refund) isBatchOperation_Operation() {}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *AccountContext        `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Operations    []*BatchOperation      `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	Atomic        bool                   `protobuf:"varint,3,opt,name=atomic,proto3" json:"atomic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{22}
}

func (x *BatchRequest) GetAccount() *AccountContext {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *BatchRequest) GetOperations() []*BatchOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *BatchRequest) GetAtomic() bool {
	if x != nil {
		return x.Atomic
	}
	return false
}

type BatchOperationResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperationId    string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Ok             bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EntryId        string                 `protobuf:"bytes,5,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	CreatedUnixUtc int64                  `protobuf:"varint,6,opt,name=created_unix_utc,json=createdUnixUtc,proto3" json:"created_unix_utc,omitempty"`
	Duplicate      bool                   `protobuf:"varint,7,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchOperationResult) Reset() {
	*x = BatchOperationResult{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperationResult) ProtoMessage() {}

func (x *BatchOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperationResult.ProtoReflect.Descriptor instead.
func (*BatchOperationResult) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{23}
}

func (x *BatchOperationResult) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *BatchOperationResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *BatchOperationResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BatchOperationResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchOperationResult) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *BatchOperationResult) GetCreatedUnixUtc() int64 {
	if x != nil {
		return x.CreatedUnixUtc
	}
	return 0
}

func (x *BatchOperationResult) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type BatchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Results       []*BatchOperationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{24}
}

func (x *BatchResponse) GetResults() []*BatchOperationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_api_credit_v1_credit_proto protoreflect.FileDescriptor

const file_api_credit_v1_credit_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/credit/v1/credit.proto\x12\tcredit.v1\"L\n" +
	"\x05Empty\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12(\n" +
	"\x10created_unix_utc\x18\x02 \x01(\x03R\x0ecreatedUnixUtc\"+\n" +
	"\x06Amount\x12!\n" +
	"\famount_cents\x18\x01 \x01(\x03R\vamountCents\"c\n" +
	"\x0eBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"[\n" +
	"\x0fBalanceResponse\x12\x1f\n" +
	"\vtotal_cents\x18\x01 \x01(\x03R\n" +
	"totalCents\x12'\n" +
	"\x0favailable_cents\x18\x02 \x01(\x03R\x0eavailableCents\"\x81\x02\n" +
	"\fGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12-\n" +
	"\x13expires_at_unix_utc\x18\x04 \x01(\x03R\x10expiresAtUnixUtc\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x06 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\"\xaa\x02\n" +
	"\x0eReserveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x06 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12-\n" +
	"\x13expires_at_unix_utc\x18\b \x01(\x03R\x10expiresAtUnixUtc\"\xfb\x01\n" +
	"\x0eCaptureRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x06 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\"\xd8\x01\n" +
	"\x0eReleaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x05 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xd2\x01\n" +
	"\fSpendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x05 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xc9\x02\n" +
	"\rRefundRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12,\n" +
	"\x11original_entry_id\x18\x04 \x01(\tH\x00R\x0foriginalEntryId\x12:\n" +
	"\x18original_idempotency_key\x18\x05 \x01(\tH\x00R\x16originalIdempotencyKey\x12!\n" +
	"\famount_cents\x18\x06 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJsonB\n" +
	"\n" +
	"\boriginal\"U\n" +
	"\x0eRefundResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12(\n" +
	"\x10created_unix_utc\x18\x02 \x01(\x03R\x0ecreatedUnixUtc\"\xf3\x02\n" +
	"\x05Entry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12%\n" +
	"\x0ereservation_id\x18\x05 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12-\n" +
	"\x13expires_at_unix_utc\x18\a \x01(\x03R\x10expiresAtUnixUtc\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\x12(\n" +
	"\x10created_unix_utc\x18\t \x01(\x03R\x0ecreatedUnixUtc\x12+\n" +
	"\x12refund_of_entry_id\x18\n" +
	" \x01(\tR\x0frefundOfEntryId\"\x98\x02\n" +
	"\x12ListEntriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fbefore_unix_utc\x18\x02 \x01(\x03R\rbeforeUnixUtc\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tledger_id\x18\x04 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\x12\x14\n" +
	"\x05types\x18\x06 \x03(\tR\x05types\x12%\n" +
	"\x0ereservation_id\x18\a \x01(\tR\rreservationId\x124\n" +
	"\x16idempotency_key_prefix\x18\b \x01(\tR\x14idempotencyKeyPrefix\"A\n" +
	"\x13ListEntriesResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.credit.v1.EntryR\aentries\"c\n" +
	"\x0eAccountContext\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"\xae\x01\n" +
	"\fBatchGrantOp\x12!\n" +
	"\famount_cents\x18\x01 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12-\n" +
	"\x13expires_at_unix_utc\x18\x03 \x01(\x03R\x10expiresAtUnixUtc\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\"\xd7\x01\n" +
	"\x0eBatchReserveOp\x12!\n" +
	"\famount_cents\x18\x01 \x01(\x03R\vamountCents\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\x12-\n" +
	"\x13expires_at_unix_utc\x18\x05 \x01(\x03R\x10expiresAtUnixUtc\"\xa8\x01\n" +
	"\x0eBatchCaptureOp\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\"\x85\x01\n" +
	"\x0eBatchReleaseOp\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"\x7f\n" +
	"\fBatchSpendOp\x12!\n" +
	"\famount_cents\x18\x01 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x03 \x01(\tR\fmetadataJson\"\xf6\x01\n" +
	"\rBatchRefundOp\x12,\n" +
	"\x11original_entry_id\x18\x01 \x01(\tH\x00R\x0foriginalEntryId\x12:\n" +
	"\x18original_idempotency_key\x18\x02 \x01(\tH\x00R\x16originalIdempotencyKey\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJsonB\n" +
	"\n" +
	"\boriginal\"\xfb\x02\n" +
	"\x0eBatchOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12/\n" +
	"\x05grant\x18\x02 \x01(\v2\x17.credit.v1.BatchGrantOpH\x00R\x05grant\x12/\n" +
	"\x05spend\x18\x03 \x01(\v2\x17.credit.v1.BatchSpendOpH\x00R\x05spend\x125\n" +
	"\areserve\x18\x04 \x01(\v2\x19.credit.v1.BatchReserveOpH\x00R\areserve\x125\n" +
	"\acapture\x18\x05 \x01(\v2\x19.credit.v1.BatchCaptureOpH\x00R\acapture\x125\n" +
	"\arelease\x18\x06 \x01(\v2\x19.credit.v1.BatchReleaseOpH\x00R\arelease\x122\n" +
	"\x06refund\x18\a \x01(\v2\x18.credit.v1.BatchRefundOpH\x00R\x06refundB\v\n" +
	"\toperation\"\x96\x01\n" +
	"\fBatchRequest\x123\n" +
	"\aaccount\x18\x01 \x01(\v2\x19.credit.v1.AccountContextR\aaccount\x129\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\x19.credit.v1.BatchOperationR\n" +
	"operations\x12\x16\n" +
	"\x06atomic\x18\x03 \x01(\bR\x06atomic\"\xf0\x01\n" +
	"\x14BatchOperationResult\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bentry_id\x18\x05 \x01(\tR\aentryId\x12(\n" +
	"\x10created_unix_utc\x18\x06 \x01(\x03R\x0ecreatedUnixUtc\x12\x1c\n" +
	"\tduplicate\x18\a \x01(\bR\tduplicate\"J\n" +
	"\rBatchResponse\x129\n" +
	"\aresults\x18\x01 \x03(\v2\x1f.credit.v1.BatchOperationResultR\aresults2\xad\x04\n" +
	"\rCreditService\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.credit.v1.BalanceRequest\x1a\x1a.credit.v1.BalanceResponse\x122\n" +
	"\x05Grant\x12\x17.credit.v1.GrantRequest\x1a\x10.credit.v1.Empty\x126\n" +
	"\aReserve\x12\x19.credit.v1.ReserveRequest\x1a\x10.credit.v1.Empty\x126\n" +
	"\aCapture\x12\x19.credit.v1.CaptureRequest\x1a\x10.credit.v1.Empty\x126\n" +
	"\aRelease\x12\x19.credit.v1.ReleaseRequest\x1a\x10.credit.v1.Empty\x122\n" +
	"\x05Spend\x12\x17.credit.v1.SpendRequest\x1a\x10.credit.v1.Empty\x12=\n" +
	"\x06Refund\x12\x18.credit.v1.RefundRequest\x1a\x19.credit.v1.RefundResponse\x12:\n" +
	"\x05Batch\x12\x17.credit.v1.BatchRequest\x1a\x18.credit.v1.BatchResponse\x12L\n" +
	"\vListEntries\x12\x1d.credit.v1.ListEntriesRequest\x1a\x1e.credit.v1.ListEntriesResponseB?Z=github.com/MarkoPoloResearchLab/ledger/api/credit/v1;creditv1b\x06proto3"

var (
	file_api_credit_v1_credit_proto_rawDescOnce sync.Once
	file_api_credit_v1_credit_proto_rawDescData []byte
)

func file_api_credit_v1_credit_proto_rawDescGZIP() []byte {
	file_api_credit_v1_credit_proto_rawDescOnce.Do(func() {
		file_api_credit_v1_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_credit_v1_credit_proto_rawDesc), len(file_api_credit_v1_credit_proto_rawDesc)))
	})
	return file_api_credit_v1_credit_proto_rawDescData
}

var file_api_credit_v1_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_credit_v1_credit_proto_goTypes = []any{
	(*Empty)(nil),                // 0: credit.v1.Empty
	(*Amount)(nil),               // 1: credit.v1.Amount
	(*BalanceRequest)(nil),       // 2: credit.v1.BalanceRequest
	(*BalanceResponse)(nil),      // 3: credit.v1.BalanceResponse
	(*GrantRequest)(nil),         // 4: credit.v1.GrantRequest
	(*ReserveRequest)(nil),       // 5: credit.v1.ReserveRequest
	(*CaptureRequest)(nil),       // 6: credit.v1.CaptureRequest
	(*ReleaseRequest)(nil),       // 7: credit.v1.ReleaseRequest
	(*SpendRequest)(nil),         // 8: credit.v1.SpendRequest
	(*RefundRequest)(nil),        // 9: credit.v1.RefundRequest
	(*RefundResponse)(nil),       // 10: credit.v1.RefundResponse
	(*Entry)(nil),                // 11: credit.v1.Entry
	(*ListEntriesRequest)(nil),   // 12: credit.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil),  // 13: credit.v1.ListEntriesResponse
	(*AccountContext)(nil),       // 14: credit.v1.AccountContext
	(*BatchGrantOp)(nil),         // 15: credit.v1.BatchGrantOp
	(*BatchReserveOp)(nil),       // 16: credit.v1.BatchReserveOp
	(*BatchCaptureOp)(nil),       // 17: credit.v1.BatchCaptureOp
	(*BatchReleaseOp)(nil),       // 18: credit.v1.BatchReleaseOp
	(*BatchSpendOp)(nil),         // 19: credit.v1.BatchSpendOp
	(*BatchRefundOp)(nil),        // 20: credit.v1.BatchRefundOp
	(*BatchOperation)(nil),       // 21: credit.v1.BatchOperation
	(*BatchRequest)(nil),         // 22: credit.v1.BatchRequest
	(*BatchOperationResult)(nil), // 23: credit.v1.BatchOperationResult
	(*BatchResponse)(nil),        // 24: credit.v1.BatchResponse
}
var file_api_credit_v1_credit_proto_depIdxs = []int32{
	11, // 0: credit.v1.ListEntriesResponse.entries:type_name -> credit.v1.Entry
	15, // 1: credit.v1.BatchOperation.grant:type_name -> credit.v1.BatchGrantOp
	19, // 2: credit.v1.BatchOperation.spend:type_name -> credit.v1.BatchSpendOp
	16, // 3: credit.v1.BatchOperation.reserve:type_name -> credit.v1.BatchReserveOp
	17, // 4: credit.v1.BatchOperation.capture:type_name -> credit.v1.BatchCaptureOp
	18, // 5: credit.v1.BatchOperation.release:type_name -> credit.v1.BatchReleaseOp
	20, // 6: credit.v1.BatchOperation.refund:type_name -> credit.v1.BatchRefundOp
	14, // 7: credit.v1.BatchRequest.account:type_name -> credit.v1.AccountContext
	21, // 8: credit.v1.BatchRequest.operations:type_name -> credit.v1.BatchOperation
	23, // 9: credit.v1.BatchResponse.results:type_name -> credit.v1.BatchOperationResult
	2,  // 10: credit.v1.CreditService.GetBalance:input_type -> credit.v1.BalanceRequest
	4,  // 11: credit.v1.CreditService.Grant:input_type -> credit.v1.GrantRequest
	5,  // 12: credit.v1.CreditService.Reserve:input_type -> credit.v1.ReserveRequest
	6,  // 13: credit.v1.CreditService.Capture:input_type -> credit.v1.CaptureRequest
	7,  // 14: credit.v1.CreditService.Release:input_type -> credit.v1.ReleaseRequest
	8,  // 15: credit.v1.CreditService.Spend:input_type -> credit.v1.SpendRequest
	9,  // 16: credit.v1.CreditService.Refund:input_type -> credit.v1.RefundRequest
	22, // 17: credit.v1.CreditService.Batch:input_type -> credit.v1.BatchRequest
	12, // 18: credit.v1.CreditService.ListEntries:input_type -> credit.v1.ListEntriesRequest
	3,  // 19: credit.v1.CreditService.GetBalance:output_type -> credit.v1.BalanceResponse
	0,  // 20: credit.v1.CreditService.Grant:output_type -> credit.v1.Empty
	0,  // 21: credit.v1.CreditService.Reserve:output_type -> credit.v1.Empty
	0,  // 22: credit.v1.CreditService.Capture:output_type -> credit.v1.Empty
	0,  // 23: credit.v1.CreditService.Release:output_type -> credit.v1.Empty
	0,  // 24: credit.v1.CreditService.Spend:output_type -> credit.v1.Empty
	10, // 25: credit.v1.CreditService.Refund:output_type -> credit.v1.RefundResponse
	24, // 26: credit.v1.CreditService.Batch:output_type -> credit.v1.BatchResponse
	13, // 27: credit.v1.CreditService.ListEntries:output_type -> credit.v1.ListEntriesResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_credit_v1_credit_proto_init() }
func file_api_credit_v1_credit_proto_init() {
	if File_api_credit_v1_credit_proto != nil {
		return
	}
	file_api_credit_v1_credit_proto_msgTypes[9].OneofWrappers = []any{
		(*RefundRequest_OriginalEntryId)(nil),
		(*RefundRequest_OriginalIdempotencyKey)(nil),
	}
	file_api_credit_v1_credit_proto_msgTypes[20].OneofWrappers = []any{
		(*BatchRefundOp_OriginalEntryId)(nil),
		(*BatchRefundOp_OriginalIdempotencyKey)(nil),
	}
	file_api_credit_v1_credit_proto_msgTypes[21].OneofWrappers = []any{
		(*BatchOperation_Grant)(nil),
		(*BatchOperation_Spend)(nil),
		(*BatchOperation_Reserve)(nil),
		(*BatchOperation_Capture)(nil),
		(*BatchOperation_Release)(nil),
		(*BatchOperation_Refund)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_credit_v1_credit_proto_rawDesc), len(file_api_credit_v1_credit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_credit_v1_credit_proto_goTypes,
		DependencyIndexes: file_api_credit_v1_credit_proto_depIdxs,
		MessageInfos:      file_api_credit_v1_credit_proto_msgTypes,
	}.Build()
	File_api_credit_v1_credit_proto = out.File
	file_api_credit_v1_credit_proto_goTypes = nil
	file_api_credit_v1_credit_proto_depIdxs = nil
}
