// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: api/credit/v1/credit.proto

package creditv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{0}
}

type Amount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AmountCents   int64                  `protobuf:"varint,1,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Amount) Reset() {
	*x = Amount{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amount) ProtoMessage() {}

func (x *Amount) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amount.ProtoReflect.Descriptor instead.
func (*Amount) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{1}
}

func (x *Amount) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

type BalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LedgerId      string                 `protobuf:"bytes,2,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceRequest) Reset() {
	*x = BalanceRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceRequest) ProtoMessage() {}

func (x *BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceRequest.ProtoReflect.Descriptor instead.
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{2}
}

func (x *BalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BalanceRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *BalanceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type BalanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalCents     int64                  `protobuf:"varint,1,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	AvailableCents int64                  `protobuf:"varint,2,opt,name=available_cents,json=availableCents,proto3" json:"available_cents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{3}
}

func (x *BalanceResponse) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *BalanceResponse) GetAvailableCents() int64 {
	if x != nil {
		return x.AvailableCents
	}
	return 0
}

type GrantRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents      int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpiresAtUnixUtc int64                  `protobuf:"varint,4,opt,name=expires_at_unix_utc,json=expiresAtUnixUtc,proto3" json:"expires_at_unix_utc,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId         string                 `protobuf:"bytes,6,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GrantRequest) Reset() {
	*x = GrantRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrantRequest) ProtoMessage() {}

func (x *GrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrantRequest.ProtoReflect.Descriptor instead.
func (*GrantRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{4}
}

func (x *GrantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GrantRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *GrantRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *GrantRequest) GetExpiresAtUnixUtc() int64 {
	if x != nil {
		return x.ExpiresAtUnixUtc
	}
	return 0
}

func (x *GrantRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *GrantRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *GrantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ReserveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents    int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	ReservationId  string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId       string                 `protobuf:"bytes,6,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{5}
}

func (x *ReserveRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *ReserveRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReserveRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *ReserveRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *ReserveRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CaptureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReservationId  string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	AmountCents    int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,5,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId       string                 `protobuf:"bytes,6,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{6}
}

func (x *CaptureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CaptureRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *CaptureRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CaptureRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *CaptureRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *CaptureRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *CaptureRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ReleaseRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReservationId  string                 `protobuf:"bytes,2,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId       string                 `protobuf:"bytes,5,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{7}
}

func (x *ReleaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReleaseRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ReleaseRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *ReleaseRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *ReleaseRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type SpendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents    int64                  `protobuf:"varint,2,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	MetadataJson   string                 `protobuf:"bytes,4,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	LedgerId       string                 `protobuf:"bytes,5,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId       string                 `protobuf:"bytes,6,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SpendRequest) Reset() {
	*x = SpendRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpendRequest) ProtoMessage() {}

func (x *SpendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpendRequest.ProtoReflect.Descriptor instead.
func (*SpendRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{8}
}

func (x *SpendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SpendRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *SpendRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SpendRequest) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *SpendRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *SpendRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Entry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntryId          string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	AccountId        string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Type             string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	AmountCents      int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	ReservationId    string                 `protobuf:"bytes,5,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpiresAtUnixUtc int64                  `protobuf:"varint,7,opt,name=expires_at_unix_utc,json=expiresAtUnixUtc,proto3" json:"expires_at_unix_utc,omitempty"`
	MetadataJson     string                 `protobuf:"bytes,8,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	CreatedUnixUtc   int64                  `protobuf:"varint,9,opt,name=created_unix_utc,json=createdUnixUtc,proto3" json:"created_unix_utc,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{9}
}

func (x *Entry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *Entry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Entry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entry) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Entry) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *Entry) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Entry) GetExpiresAtUnixUtc() int64 {
	if x != nil {
		return x.ExpiresAtUnixUtc
	}
	return 0
}

func (x *Entry) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *Entry) GetCreatedUnixUtc() int64 {
	if x != nil {
		return x.CreatedUnixUtc
	}
	return 0
}

type ListEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BeforeUnixUtc int64                  `protobuf:"varint,2,opt,name=before_unix_utc,json=beforeUnixUtc,proto3" json:"before_unix_utc,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	LedgerId      string                 `protobuf:"bytes,4,opt,name=ledger_id,json=ledgerId,proto3" json:"ledger_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{10}
}

func (x *ListEntriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListEntriesRequest) GetBeforeUnixUtc() int64 {
	if x != nil {
		return x.BeforeUnixUtc
	}
	return 0
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEntriesRequest) GetLedgerId() string {
	if x != nil {
		return x.LedgerId
	}
	return ""
}

func (x *ListEntriesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_api_credit_v1_credit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_credit_v1_credit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_credit_v1_credit_proto_rawDescGZIP(), []int{11}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_api_credit_v1_credit_proto protoreflect.FileDescriptor

const file_api_credit_v1_credit_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/credit/v1/credit.proto\x12\tcredit.v1\"\a\n" +
	"\x05Empty\"+\n" +
	"\x06Amount\x12!\n" +
	"\famount_cents\x18\x01 \x01(\x03R\vamountCents\"c\n" +
	"\x0eBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tledger_id\x18\x02 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"[\n" +
	"\x0fBalanceResponse\x12\x1f\n" +
	"\vtotal_cents\x18\x01 \x01(\x03R\n" +
	"totalCents\x12'\n" +
	"\x0favailable_cents\x18\x02 \x01(\x03R\x0eavailableCents\"\x81\x02\n" +
	"\fGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12-\n" +
	"\x13expires_at_unix_utc\x18\x04 \x01(\x03R\x10expiresAtUnixUtc\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x06 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\"\xfb\x01\n" +
	"\x0eReserveRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x06 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\"\xfb\x01\n" +
	"\x0eCaptureRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12#\n" +
	"\rmetadata_json\x18\x05 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x06 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\"\xd8\x01\n" +
	"\x0eReleaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12%\n" +
	"\x0ereservation_id\x18\x02 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x05 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xd2\x01\n" +
	"\fSpendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x02 \x01(\x03R\vamountCents\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12#\n" +
	"\rmetadata_json\x18\x04 \x01(\tR\fmetadataJson\x12\x1b\n" +
	"\tledger_id\x18\x05 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x06 \x01(\tR\btenantId\"\xc6\x02\n" +
	"\x05Entry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12%\n" +
	"\x0ereservation_id\x18\x05 \x01(\tR\rreservationId\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12-\n" +
	"\x13expires_at_unix_utc\x18\a \x01(\x03R\x10expiresAtUnixUtc\x12#\n" +
	"\rmetadata_json\x18\b \x01(\tR\fmetadataJson\x12(\n" +
	"\x10created_unix_utc\x18\t \x01(\x03R\x0ecreatedUnixUtc\"\xa5\x01\n" +
	"\x12ListEntriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0fbefore_unix_utc\x18\x02 \x01(\x03R\rbeforeUnixUtc\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tledger_id\x18\x04 \x01(\tR\bledgerId\x12\x1b\n" +
	"\ttenant_id\x18\x05 \x01(\tR\btenantId\"A\n" +
	"\x13ListEntriesResponse\x12*\n" +
	"\aentries\x18\x01 \x03(\v2\x10.credit.v1.EntryR\aentries2\xb2\x03\n" +
	"\rCreditService\x12C\n" +
	"\n" +
	"GetBalance\x12\x19.credit.v1.BalanceRequest\x1a\x1a.credit.v1.BalanceResponse\x122\n" +
	"\x05Grant\x12\x17.credit.v1.GrantRequest\x1a\x10.credit.v1.Empty\x126\n" +
	"\aReserve\x12\x19.credit.v1.ReserveRequest\x1a\x10.credit.v1.Empty\x126\n" +
	"\aCapture\x12\x19.credit.v1.CaptureRequest\x1a\x10.credit.v1.Empty\x126\n" +
	"\aRelease\x12\x19.credit.v1.ReleaseRequest\x1a\x10.credit.v1.Empty\x122\n" +
	"\x05Spend\x12\x17.credit.v1.SpendRequest\x1a\x10.credit.v1.Empty\x12L\n" +
	"\vListEntries\x12\x1d.credit.v1.ListEntriesRequest\x1a\x1e.credit.v1.ListEntriesResponseB?Z=github.com/MarkoPoloResearchLab/ledger/api/credit/v1;creditv1b\x06proto3"

var (
	file_api_credit_v1_credit_proto_rawDescOnce sync.Once
	file_api_credit_v1_credit_proto_rawDescData []byte
)

func file_api_credit_v1_credit_proto_rawDescGZIP() []byte {
	file_api_credit_v1_credit_proto_rawDescOnce.Do(func() {
		file_api_credit_v1_credit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_credit_v1_credit_proto_rawDesc), len(file_api_credit_v1_credit_proto_rawDesc)))
	})
	return file_api_credit_v1_credit_proto_rawDescData
}

var file_api_credit_v1_credit_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_credit_v1_credit_proto_goTypes = []any{
	(*Empty)(nil),               // 0: credit.v1.Empty
	(*Amount)(nil),              // 1: credit.v1.Amount
	(*BalanceRequest)(nil),      // 2: credit.v1.BalanceRequest
	(*BalanceResponse)(nil),     // 3: credit.v1.BalanceResponse
	(*GrantRequest)(nil),        // 4: credit.v1.GrantRequest
	(*ReserveRequest)(nil),      // 5: credit.v1.ReserveRequest
	(*CaptureRequest)(nil),      // 6: credit.v1.CaptureRequest
	(*ReleaseRequest)(nil),      // 7: credit.v1.ReleaseRequest
	(*SpendRequest)(nil),        // 8: credit.v1.SpendRequest
	(*Entry)(nil),               // 9: credit.v1.Entry
	(*ListEntriesRequest)(nil),  // 10: credit.v1.ListEntriesRequest
	(*ListEntriesResponse)(nil), // 11: credit.v1.ListEntriesResponse
}
var file_api_credit_v1_credit_proto_depIdxs = []int32{
	9,  // 0: credit.v1.ListEntriesResponse.entries:type_name -> credit.v1.Entry
	2,  // 1: credit.v1.CreditService.GetBalance:input_type -> credit.v1.BalanceRequest
	4,  // 2: credit.v1.CreditService.Grant:input_type -> credit.v1.GrantRequest
	5,  // 3: credit.v1.CreditService.Reserve:input_type -> credit.v1.ReserveRequest
	6,  // 4: credit.v1.CreditService.Capture:input_type -> credit.v1.CaptureRequest
	7,  // 5: credit.v1.CreditService.Release:input_type -> credit.v1.ReleaseRequest
	8,  // 6: credit.v1.CreditService.Spend:input_type -> credit.v1.SpendRequest
	10, // 7: credit.v1.CreditService.ListEntries:input_type -> credit.v1.ListEntriesRequest
	3,  // 8: credit.v1.CreditService.GetBalance:output_type -> credit.v1.BalanceResponse
	0,  // 9: credit.v1.CreditService.Grant:output_type -> credit.v1.Empty
	0,  // 10: credit.v1.CreditService.Reserve:output_type -> credit.v1.Empty
	0,  // 11: credit.v1.CreditService.Capture:output_type -> credit.v1.Empty
	0,  // 12: credit.v1.CreditService.Release:output_type -> credit.v1.Empty
	0,  // 13: credit.v1.CreditService.Spend:output_type -> credit.v1.Empty
	11, // 14: credit.v1.CreditService.ListEntries:output_type -> credit.v1.ListEntriesResponse
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_credit_v1_credit_proto_init() }
func file_api_credit_v1_credit_proto_init() {
	if File_api_credit_v1_credit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_credit_v1_credit_proto_rawDesc), len(file_api_credit_v1_credit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_credit_v1_credit_proto_goTypes,
		DependencyIndexes: file_api_credit_v1_credit_proto_depIdxs,
		MessageInfos:      file_api_credit_v1_credit_proto_msgTypes,
	}.Build()
	File_api_credit_v1_credit_proto = out.File
	file_api_credit_v1_credit_proto_goTypes = nil
	file_api_credit_v1_credit_proto_depIdxs = nil
}
