# build stage
FROM golang:1.25-alpine AS build
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN apk add --no-cache git
RUN go install github.com/MarkoPoloResearchLab/ledger/cmd/ledger@latest

# runtime stage
FROM alpine:3.20
WORKDIR /srv
RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/ledger /srv/ledgerd
ENV GRPC_LISTEN_ADDR=:50051
EXPOSE 50051
USER root
CMD ["/srv/ledgerd"]
