# build stage
FROM golang:1.25-alpine AS build
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64
RUN apk add --no-cache git
RUN go install github.com/MarkoPoloResearchLab/ledger/cmd/demoapi@latest

# runtime stage
FROM alpine:3.20
WORKDIR /srv
RUN apk add --no-cache ca-certificates
COPY --from=build /go/bin/demoapi /srv/demoapi
ENV DEMOAPI_LISTEN_ADDR=:9090
EXPOSE 9090
USER root
CMD ["/srv/demoapi"]
